package org.isk.jvmhardcore.math.parser.core.util;

public interface Ascii {
  public static final byte EOF = -1;
  public static final char NULL = 0;
  public static final char TAB = 0x09; // \t
  public static final char LF = 0x0A; // \n
  public static final char CR = 0x0D; // \r
  public static final char SPACE = 0x20; // ' '
  public static final char EXCLAMATION_MARK = 0x21; // !
  public static final char QUOTATION_MARK = 0x22; // "
  public static final char NUMBER_SIGN = 0x23; // #
  public static final char DOLLAR_SIGN = 0x24; // $
  public static final char PERCENT_SIGN = 0x25; // %
  public static final char AMPERSAND = 0x26; // &
  public static final char SINGLE_QUOTE = 0x27; // '
  public static final char LEFT_PARENTHESIS = 0x28; // (
  public static final char RIGHT_PARENTHESIS = 0x29; // )
  public static final char ASTERISK = 0x2A; // *
  public static final char PLUS_SIGN = 0x2B; // +
  public static final char COMMA = 0x2C; // ,
  public static final char HYPHEN = 0x2D; // -
  public static final char PERIOD = 0x2E; // .
  public static final char SLASH = 0x2F; // /
  public static final char DIGIT_0 = 0x30;
  public static final char DIGIT_1 = 0x31;
  public static final char DIGIT_2 = 0x32;
  public static final char DIGIT_3 = 0x33;
  public static final char DIGIT_4 = 0x34;
  public static final char DIGIT_5 = 0x35;
  public static final char DIGIT_6 = 0x36;
  public static final char DIGIT_7 = 0x37;
  public static final char DIGIT_8 = 0x38;
  public static final char DIGIT_9 = 0x39;
  public static final char COLON = 0x3A; // :
  public static final char SEMICOLON = 0x3B; // ;
  public static final char LESS_THAN = 0x3C; // <
  public static final char EQUALS = 0x3D; // =
  public static final char GREATER_THAN = 0x3E; // >
  public static final char QUESTION_MARK = 0x3F; // ?
  public static final char COMMERCIAL_AT = 0x40; // @
  public static final char UPPERCASE_A = 0x41; // A
  public static final char UPPERCASE_B = 0x42; //
  public static final char UPPERCASE_C = 0x43; //
  public static final char UPPERCASE_D = 0x44; //
  public static final char UPPERCASE_E = 0x45; //
  public static final char UPPERCASE_F = 0x46; //
  public static final char UPPERCASE_G = 0x47; //
  public static final char UPPERCASE_H = 0x48; //
  public static final char UPPERCASE_I = 0x49; //
  public static final char UPPERCASE_J = 0x4A; //
  public static final char UPPERCASE_K = 0x4B; //
  public static final char UPPERCASE_L = 0x4C; //
  public static final char UPPERCASE_M = 0x4D; //
  public static final char UPPERCASE_N = 0x4E; //
  public static final char UPPERCASE_O = 0x4F; //
  public static final char UPPERCASE_P = 0x50; //
  public static final char UPPERCASE_Q = 0x51; //
  public static final char UPPERCASE_R = 0x52; //
  public static final char UPPERCASE_S = 0x53; //
  public static final char UPPERCASE_T = 0x54; //
  public static final char UPPERCASE_U = 0x55; //
  public static final char UPPERCASE_V = 0x56; //
  public static final char UPPERCASE_W = 0x57; //
  public static final char UPPERCASE_X = 0x58; //
  public static final char UPPERCASE_Y = 0x59; //
  public static final char UPPERCASE_Z = 0x5A; // Z
  public static final char LEFT_BRACKET = 0x5B; // [
  public static final char REVERSE_SLANT = 0x5C; // \
  public static final char RIGHT_BRACKET = 0x5D; // ]
  public static final char CIRCUMFLEX_ACCENT = 0x5E; // ^
  public static final char UNDERSCORE = 0x5F; // _
  public static final char GRAVE_ACCENT = 0x60; // `
  public static final char LOWERCASE_A = 0x61; // a
  public static final char LOWERCASE_B = 0x62; //
  public static final char LOWERCASE_C = 0x63; //
  public static final char LOWERCASE_D = 0x64; //
  public static final char LOWERCASE_E = 0x65; //
  public static final char LOWERCASE_F = 0x66; //
  public static final char LOWERCASE_G = 0x67; //
  public static final char LOWERCASE_H = 0x68; //
  public static final char LOWERCASE_I = 0x69; //
  public static final char LOWERCASE_J = 0x6A; //
  public static final char LOWERCASE_K = 0x6B; //
  public static final char LOWERCASE_L = 0x6C; //
  public static final char LOWERCASE_M = 0x6D; //
  public static final char LOWERCASE_N = 0x6E; //
  public static final char LOWERCASE_O = 0x6F; //
  public static final char LOWERCASE_P = 0x70; //
  public static final char LOWERCASE_Q = 0x71; //
  public static final char LOWERCASE_R = 0x72; //
  public static final char LOWERCASE_S = 0x73; //
  public static final char LOWERCASE_T = 0x74; //
  public static final char LOWERCASE_U = 0x75; //
  public static final char LOWERCASE_V = 0x76; //
  public static final char LOWERCASE_W = 0x77; //
  public static final char LOWERCASE_X = 0x78; //
  public static final char LOWERCASE_Y = 0x79; //
  public static final char LOWERCASE_Z = 0x7A; // z
  public static final char LEFT_BRACE = 0x7B; // {
  public static final char VERTICAL_BAR = 0x7B; // |
  public static final char RIGHT_BRACE = 0x7D; // }
  public static final char TILDE = 0x7D; // ~
}
